name: Main

on: [push]

jobs:
  check_coverage:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Haskell
        uses: ./actions/haskell-setup
        with:
          ghc-version: 9.10.1
          cabal-version: 3.12.1.0

      - name: Build and test
        run: |
          cabal update
          cabal install hspec-discover hpc-codecov
          cabal configure --enable-coverage
          cabal build
          cabal test

      - name: Generate coverage report
        run: |
          hpc-codecov cabal:glados-test --exclude Main,Paths_glados --out codecov.json --format codecov --verbose

      - name: Send coverage report
        uses: codecov/codecov-action@v3
