name: Main

on: [push]

jobs:
  check_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: 9.10.1
          cabal-version: 3.12.1.0

      - name: Build and test
        run: |
          cabal update
          cabal configure --enable-coverage
          cabal build
          cabal test

      - name: Generate coverage report
        uses: 8c6794b6/hpc-codecov-action@v4
        with:
          target: cabal:glados-test
          excludes: Main,Paths_glados

      - name: Send coverage report
        uses: codecov/codecov-action@v3
