name: Main

on: [push]

jobs:
  check_coverage:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache GHCup
        uses: actions/cache@v4
        with:
          path: /home/runner/.ghcup
          key: ${{ runner.os }}-ghcup-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-ghcup-

      - name: Cache Cabal
        uses: actions/cache@v4
        with:
          path: /home/runner/.cabal
          key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-cabal-

      - name: Install required packages
        run: sudo apt update && sudo apt install -y build-essential libffi-dev libgmp-dev zlib1g-dev

      - name: Setup Haskell
        uses: ./actions/haskell-setup
        with:
          ghc-version: 9.10.1
          cabal-version: 3.12.1.0

      - name: Build and test
        run: |
          cabal update
          cabal install hspec-discover hpc-codecov
          cabal configure --enable-coverage
          cabal build --jobs=1
          cabal test --jobs=1

      - name: Generate coverage report
        run: |
          hpc-codecov cabal:glados-test --exclude Main,Paths_glados --out codecov.json --format codecov --verbose

      - name: Send coverage report
        uses: codecov/codecov-action@v5
